databases:
  - name: aura-farming-db
    databaseName: aura_farming
    plan: free

services:
  - type: web
    name: aura-farming
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn aura_farming.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aura-farming-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
